@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 17 18:01:19 +0300 2022
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim proc_mc_testbench_huge_behav -key {Behavioral:sim_proc_mc:Functional:proc_mc_testbench_huge} -tclbatch proc_mc_testbench_huge.tcl -view C:/Users/user/Mips Processor/MC_Waveforms/decryption_test_mc.wcfg -log simulate.log"
call xsim  proc_mc_testbench_huge_behav -key {Behavioral:sim_proc_mc:Functional:proc_mc_testbench_huge} -tclbatch proc_mc_testbench_huge.tcl -view C:/Users/user/Mips Processor/MC_Waveforms/decryption_test_mc.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
